name: Verify

on:
  - push

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x
      - name: Run bundle audit
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bin/audit

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x
      - name: Run linter
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bin/lint

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x
      - name: Run tests
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          COVERALLS_GIT_BRANCH="${GITHUB_REF/refs\/heads\//}" bin/test
